param([string]$WolvenKitPath='F:\Program Files\GOG Galaxy\Games\my mods\WolvenKit-8.20.0.zip 2201 8.20.0 2026-08-06T08-14Z xNHtNXgDX')
$ErrorActionPreference='Stop'
Get-ChildItem $WolvenKitPath -Filter '*.dll' | ForEach-Object {try {[Reflection.Assembly]::LoadFrom($_.FullName)|Out-Null}catch{}}
if(![WolvenKit.Core.Compression.Oodle]::Load('F:\Program Files\GOG Galaxy\Games\Cyberpunk 2077\bin\x64\oo2ext_7_win64.dll')){throw 'Could not load game compression library'}
$root=Split-Path $PSScriptRoot -Parent
$assets=Join-Path $root 'tmp\display-prototype'
$gamePath='F:\Program Files\GOG Galaxy\Games\Cyberpunk 2077'
$interiorAsset='base\vehicles\special\v_mahir_mt28_coach\entities\v_mahir_mt28_coach__ext01_interior_01.ent'

# Remove only the retired root-entity override. The widget generated by the
# companion script remains under nctc\ui and must be preserved.
$retiredEntity=Join-Path $assets 'nctc\vehicles\mahir_display.ent'
if(Test-Path -LiteralPath $retiredEntity){Remove-Item -LiteralPath $retiredEntity -Force}

# A WorldWidget must be mounted on a real mesh component.  The first
# prototype put it on the vehicle root and left MeshTargetBinding empty;
# REDengine dereferenced that empty binding while spawning the bus.
$hash=[WolvenKit.Common.Services.HashService]::new()
$hash.Load()
$archiveReader=[WolvenKit.RED4.Archive.IO.ArchiveReader]::new()
function Read-GameAsset([string]$asset) {
  $assetId=[WolvenKit.Common.FNV1A.FNV1A64HashAlgorithm]::HashString($asset)
  foreach($archiveFile in Get-ChildItem (Join-Path $gamePath 'archive\pc\content') -Filter '*.archive') {
    $archive=$null
    $null=$archiveReader.ReadArchive($archiveFile.FullName,$hash,[ref]$archive)
    if(!$archive.Files.ContainsKey($assetId)){continue}
    $inputStream=[IO.MemoryStream]::new()
    try {
      $archive.ExtractFile($archive.Files[$assetId],$inputStream)
      $inputStream.Position=0
      $reader=[WolvenKit.RED4.Archive.IO.CR2WReader]::new($inputStream)
      $file=$null
      $result=$reader.ReadFile([ref]$file,$true)
      if($result.ToString() -ne 'NoError'){throw "Could not read $asset"}
      return $file
    } finally {$inputStream.Dispose()}
  }
  throw "Could not find game asset: $asset"
}

$file=Read-GameAsset $interiorAsset
$package=$file.RootChunk.CompiledData.Data
$originalCount=$package.Chunks.Count
# Copy NCART's real screen/WorldWidget pair. Each copy is read afresh so no
# mutable component state or CRUID is shared between displays.
function Add-DisplayPair(
  [string]$name,
  [string]$item,
  [UInt64]$id,
  [single]$x,[single]$y,[single]$z,
  [single]$qi,[single]$qj,[single]$qk,[single]$qr,
  [single]$width,[single]$height
) {
  $metroTemplate=Read-GameAsset 'base\open_world\metro\ue_metro\entities\ue_metro_train.ent'
  $screen=$metroTemplate.RootChunk.Components | Where-Object {$_.Name.ToString() -eq 'screen5558'} | Select-Object -First 1
  $widget=$metroTemplate.RootChunk.Components | Where-Object {$_.Name.ToString() -eq 'dataTerm_ui5441'} | Select-Object -First 1
  if($null -eq $screen -or $null -eq $widget){throw 'Could not locate the vanilla NCART screen component pair'}
  $screenName="nctc_${name}_screen"
  $screen.Name=[WolvenKit.RED4.Types.CName]$screenName
  $screen.Id=[WolvenKit.RED4.Types.CRUID]$id
  $screen.LocalTransform.Position.X=[WolvenKit.RED4.Types.FixedPoint]$x
  $screen.LocalTransform.Position.Y=[WolvenKit.RED4.Types.FixedPoint]$y
  $screen.LocalTransform.Position.Z=[WolvenKit.RED4.Types.FixedPoint]$z
  $screen.LocalTransform.Orientation.I=[WolvenKit.RED4.Types.CFloat]$qi
  $screen.LocalTransform.Orientation.J=[WolvenKit.RED4.Types.CFloat]$qj
  $screen.LocalTransform.Orientation.K=[WolvenKit.RED4.Types.CFloat]$qk
  $screen.LocalTransform.Orientation.R=[WolvenKit.RED4.Types.CFloat]$qr
  $screen.VisualScale.X=[WolvenKit.RED4.Types.CFloat]$width
  $screen.VisualScale.Y=[WolvenKit.RED4.Types.CFloat][single]0.05
  $screen.VisualScale.Z=[WolvenKit.RED4.Types.CFloat]$height
  $screenParent=[WolvenKit.RED4.Types.entHardTransformBinding]::new()
  $screenParent.BindName=[WolvenKit.RED4.Types.CName]'deformation_rig'
  $screen.ParentTransform=[WolvenKit.RED4.Types.CHandle[WolvenKit.RED4.Types.entITransformBinding]]::new($screenParent)

  $widget.Name=[WolvenKit.RED4.Types.CName]("nctc_${name}_display")
  $widget.Id=[WolvenKit.RED4.Types.CRUID]($id+1)
  $widget.WidgetResource=[WolvenKit.RED4.Types.CResourceAsyncReference[WolvenKit.RED4.Types.inkWidgetLibraryResource]]::new('nctc\ui\bus_display.inkwidget')
  $widget.ItemNameToSpawn=[WolvenKit.RED4.Types.CName]$item
  $widget.LimitedSpawnDistanceFromVehicle=[WolvenKit.RED4.Types.CBool]$false
  $widget.SpawnDistanceOverride=[WolvenKit.RED4.Types.CFloat][single]50
  $widget.SceneWidgetProperties.IsAlwaysVisible=[WolvenKit.RED4.Types.CBool]$true
  $widget.SceneWidgetProperties.IsInteractable=[WolvenKit.RED4.Types.CBool]$false
  $widget.ScreenAreaMultiplier=[WolvenKit.RED4.Types.CFloat][single]2
  $meshBinding=[WolvenKit.RED4.Types.worlduiMeshTargetBinding]::new()
  $meshBinding.BindName=[WolvenKit.RED4.Types.CName]$screenName
  $widget.MeshTargetBinding=[WolvenKit.RED4.Types.CHandle[WolvenKit.RED4.Types.worlduiMeshTargetBinding]]::new($meshBinding)
  $binding=[WolvenKit.RED4.Types.entHardTransformBinding]::new()
  $binding.BindName=[WolvenKit.RED4.Types.CName]$screenName
  $widget.ParentTransform=[WolvenKit.RED4.Types.CHandle[WolvenKit.RED4.Types.entITransformBinding]]::new($binding)
  $file.RootChunk.Components.Add($screen)
  $file.RootChunk.Components.Add($widget)
}

# Vehicle-local axes: X left/right, Y rear/front, Z up. The first pair is the
# passenger-facing display above the windscreen. The remaining pairs cover the
# vanilla route-number / next-stop positions outside the coach.
Add-DisplayPair 'interior_route' 'Route' 90170000000000  0.45  4.79 1.93  0 0 0 1                 0.78 0.12
Add-DisplayPair 'front_line'    'Line'  90170000000010  0.74  5.08 2.38  0 0 0 1                 0.25 0.12
Add-DisplayPair 'front_route'   'Route' 90170000000020 -0.38  5.08 2.38  0 0 0 1                 0.62 0.12
Add-DisplayPair 'right_route'   'Route' 90170000000030 -1.31 -2.65 2.20  0 0 -0.7071068 0.7071068 0.72 0.12
Add-DisplayPair 'left_route'    'Route' 90170000000040  1.31 -2.65 2.20  0 0  0.7071068 0.7071068 0.72 0.12
Add-DisplayPair 'rear_line'     'Line'  90170000000050  0.00 -5.10 2.30  0 0 1 0                 0.30 0.12

# WolvenKit rebuilds compiledData from Entity + Components before writing.
# Editing the parsed package alone is discarded by its preprocessor.
$path=Join-Path $assets $interiorAsset
New-Item -ItemType Directory -Force (Split-Path $path -Parent)|Out-Null
$stream=[IO.File]::Create($path)
try {$writer=[WolvenKit.RED4.Archive.IO.CR2WWriter]::new($stream);$writer.WriteFile($file)}finally{$stream.Dispose()}
$stream=[IO.File]::OpenRead($path)
try {
  $reader=[WolvenKit.RED4.Archive.IO.CR2WReader]::new($stream)
  $check=$null
  $result=$reader.ReadFile([ref]$check,$true)
  $count=$check.RootChunk.CompiledData.Data.Chunks.Count
  if($result.ToString() -ne 'NoError' -or $count -ne ($originalCount+12)){throw "Bus template round-trip failed: $result count=$count expected=$($originalCount+12)"}
}finally{$stream.Dispose()}
$archivePath=Join-Path $root 'tmp\NCTCDisplayPrototype.archive'
$stream=[IO.File]::Create($archivePath)
try {
  $writer=[WolvenKit.RED4.Archive.IO.ArchiveWriter]::new($hash,$null)
  if(!$writer.WriteArchive([IO.DirectoryInfo]::new($assets),$stream)){throw 'Archive packaging failed'}
}finally{$stream.Dispose()}
Write-Output "Verified template and packaged display: $archivePath"
